(() => {
  'use strict';
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false}),wrap=document.getElementById('gameWrap'),overlay=document.getElementById('overlay'),overlayText=document.getElementById('overlayText'),startBtn=document.getElementById('startBtn'),pauseBtn=document.getElementById('pauseBtn'),muteBtn=document.getElementById('muteBtn'),calibrateBtn=document.getElementById('calibrateBtn'),sensorStatus=document.getElementById('sensorStatus'),scoreEl=document.getElementById('score'),levelEl=document.getElementById('level'),livesEl=document.getElementById('lives'),timeEl=document.getElementById('time'),bestEl=document.getElementById('best'),banner=document.getElementById('banner'),tiltDot=document.getElementById('tiltDot'),touchStick=document.getElementById('touchStick'),stickKnob=touchStick.querySelector('i');
  const Levels=window.NeonTiltLevels,Physics=window.NeonTiltPhysics,Renderer=window.NeonTiltRender;if(!Levels||!Physics||!Renderer)throw new Error('Neon Tilt modules missing');
  const BEST_KEY='rwgNeonTiltBest';let best=Number(localStorage.getItem(BEST_KEY)||0);bestEl.textContent=best.toLocaleString('it-IT');
  const state={running:false,paused:false,score:0,level:1,lives:3,levelTime:0,totalTime:0,cssW:320,cssH:480,cell:24,world:null,ball:{x:1.5,y:1.5,vx:0,vy:0,r:.29},particles:[],input:{x:0,y:0},sensorInput:{x:0,y:0},keyInput:{x:0,y:0},touchInput:{x:0,y:0,active:false},last:performance.now(),respawnLock:0,mute:false,sensor:{available:'DeviceOrientationEvent'in window,permission:'unknown',active:false,beta:0,gamma:0,baseBeta:0,baseGamma:0,smoothBeta:0,smoothGamma:0,samples:[]}};
  let audioCtx=null;const audio=(freq=440,duration=.06,type='square',gain=.035)=>{if(state.mute)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration);}catch(_){}};
  const vibrate=p=>{try{navigator.vibrate?.(p);}catch(_){}},fmt=n=>Number(n).toLocaleString('it-IT'),fmtTime=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
  const setBanner=text=>{banner.textContent=text;banner.classList.remove('show');requestAnimationFrame(()=>banner.classList.add('show'));};
  function resize(){const rect=wrap.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);state.cssW=Math.max(1,rect.width);state.cssH=Math.max(1,rect.height);canvas.width=Math.round(state.cssW*dpr);canvas.height=Math.round(state.cssH*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(state.world)rebuildScaleOnly();}
  function parseLevel(index){const def=Levels[(index-1)%Levels.length],rows=def.map.length,cols=def.map[0].length,world={def,rows,cols,walls:[],pits:[],bumpers:[],ice:[],boosts:[],shards:[],start:null,goal:null},dirs={'>':[1,0],'<':[-1,0],'^':[0,-1],'v':[0,1]};def.map.forEach((row,y)=>[...row].forEach((ch,x)=>{if(ch==='#')world.walls.push({x,y,w:1,h:1});if(ch==='S')world.start={x:x+.5,y:y+.5};if(ch==='G')world.goal={x:x+.5,y:y+.5,r:.34};if(ch==='O')world.pits.push({x:x+.5,y:y+.5,r:.36});if(ch==='B')world.bumpers.push({x:x+.5,y:y+.5,r:.31});if(ch==='~')world.ice.push({x,y,w:1,h:1});if(ch==='*')world.shards.push({x:x+.5,y:y+.5,r:.16,collected:false,phase:Math.random()*Math.PI*2});if(dirs[ch])world.boosts.push({cx:x+.5,cy:y+.5,dx:dirs[ch][0],dy:dirs[ch][1]});}));world.surfaceAt=(x,y)=>def.map[Math.floor(y)]?.[Math.floor(x)]||'#';world.boostAt=(x,y)=>{const tx=Math.floor(x)+.5,ty=Math.floor(y)+.5,b=world.boosts.find(v=>v.cx===tx&&v.cy===ty);return b?{x:b.dx,y:b.dy}:null;};return world;}
  function rebuildScaleOnly(){if(!state.world)return;state.cell=Math.min(state.cssW/state.world.cols,state.cssH/state.world.rows);const usedW=state.cell*state.world.cols,usedH=state.cell*state.world.rows;state.boardW=usedW;state.boardH=usedH;state.offsetX=(state.cssW-usedW)/2;state.offsetY=(state.cssH-usedH)/2;}
  function loadLevel(level,preserveScore=true){state.level=level;state.world=parseLevel(level);state.levelTime=0;state.ball.x=state.world.start.x;state.ball.y=state.world.start.y;state.ball.vx=state.ball.vy=0;state.respawnLock=.55;state.particles.length=0;levelEl.textContent=state.level;if(!preserveScore)state.score=0;scoreEl.textContent=fmt(state.score);resize();setBanner(`LEVEL ${state.level} • ${state.world.def.name}`);}
  function updateHud(){scoreEl.textContent=fmt(state.score);levelEl.textContent=state.level;livesEl.textContent=state.lives;timeEl.textContent=fmtTime(state.totalTime);}
  function addParticles(x,y,color,count=8){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=.7+Math.random()*2.4;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.6+Math.random()*.35,size:.035+Math.random()*.055,color});}}
  function loseLife(reason='CADUTA!'){if(state.respawnLock>0||!state.running)return;state.lives--;updateHud();audio(110,.18,'sawtooth',.055);vibrate([35,25,55]);setBanner(reason);if(state.lives<=0){gameOver();return;}state.ball.x=state.world.start.x;state.ball.y=state.world.start.y;state.ball.vx=state.ball.vy=0;state.respawnLock=1;}
  function collectShard(shard){shard.collected=true;state.score+=150*state.level;addParticles(shard.x,shard.y,'#7cffb2',10);audio(680+Math.min(600,state.level*25),.07,'triangle',.04);vibrate(12);updateHud();if(state.world.shards.every(s=>s.collected))setBanner('PORTALE APERTO!');}
  function clearLevel(){const par=state.world.def.par,timeBonus=Math.max(0,Math.round((par-state.levelTime)*30)),base=850+state.level*130;state.score+=base+timeBonus;audio(880,.08,'triangle',.05);setTimeout(()=>audio(1175,.12,'triangle',.045),90);vibrate([18,28,18]);updateHud();const next=state.level+1;setBanner(`CLEAR +${fmt(base+timeBonus)}`);state.running=false;setTimeout(()=>{if(overlay.classList.contains('visible'))return;loadLevel(next);state.running=true;state.last=performance.now();},760);}
  function gameOver(){state.running=false;state.paused=false;pauseBtn.textContent='Ⅱ';if(state.score>best){best=state.score;localStorage.setItem(BEST_KEY,String(best));bestEl.textContent=fmt(best);}overlayText.textContent=`Run terminata al livello ${state.level}. Punteggio ${fmt(state.score)}.`;startBtn.textContent='RIGIOCA';overlay.classList.add('visible');window.dispatchEvent(new CustomEvent('rwg:game-ended',{detail:{game:'Neon Tilt',score:state.score,level:state.level,best,activeMs:state.totalTime*1000}}));requestAnimationFrame(()=>window.RWGGameOver?.open?.({score:state.score,level:state.level,best,activeMs:state.totalTime*1000}));}
  function startGame(){state.score=0;state.lives=3;state.totalTime=0;state.paused=false;pauseBtn.textContent='Ⅱ';loadLevel(1,false);overlay.classList.remove('visible');state.running=true;state.last=performance.now();updateHud();}
  function onOrientation(e){if(!Number.isFinite(e.beta)||!Number.isFinite(e.gamma))return;const s=state.sensor;s.beta=e.beta;s.gamma=e.gamma;if(!s.active){s.active=true;sensorStatus.classList.add('active');sensorStatus.querySelector('span').textContent='TILT';}s.smoothBeta+=(s.beta-s.smoothBeta)*.2;s.smoothGamma+=(s.gamma-s.smoothGamma)*.2;if(s.samples)s.samples.push([s.beta,s.gamma]);}
  async function requestSensorPermission(){const s=state.sensor;if(!s.available){s.permission='unavailable';sensorStatus.querySelector('span').textContent='TOUCH';return false;}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const result=await DeviceOrientationEvent.requestPermission();s.permission=result;if(result!=='granted'){sensorStatus.querySelector('span').textContent='TOUCH';return false;}}else s.permission='granted';window.removeEventListener('deviceorientation',onOrientation);window.addEventListener('deviceorientation',onOrientation,{passive:true});return true;}catch(_){s.permission='denied';sensorStatus.querySelector('span').textContent='TOUCH';return false;}}
  async function calibrate(showMessage=true){const s=state.sensor;if(s.permission!=='granted')return false;s.samples=[];sensorStatus.classList.add('calibrating');sensorStatus.querySelector('span').textContent='CAL...';if(showMessage)setBanner('TIENI IL TELEFONO COMODO...');await new Promise(r=>setTimeout(r,480));const samples=s.samples||[];s.samples=null;if(samples.length){const tail=samples.slice(-Math.min(samples.length,24));s.baseBeta=tail.reduce((a,v)=>a+v[0],0)/tail.length;s.baseGamma=tail.reduce((a,v)=>a+v[1],0)/tail.length;s.smoothBeta=s.baseBeta;s.smoothGamma=s.baseGamma;}else{s.baseBeta=s.beta;s.baseGamma=s.gamma;}sensorStatus.classList.remove('calibrating');sensorStatus.classList.add('active');sensorStatus.querySelector('span').textContent='TILT';if(showMessage)setBanner('CALIBRATO ✓');return true;}
  function getSensorInput(){const s=state.sensor;if(s.permission!=='granted'||!s.active)return{x:0,y:0};const dead=1.25,maxTilt=22;let dx=s.smoothGamma-s.baseGamma,dy=s.smoothBeta-s.baseBeta;dx=Math.abs(dx)<dead?0:dx-Math.sign(dx)*dead;dy=Math.abs(dy)<dead?0:dy-Math.sign(dy)*dead;return{x:Physics.clamp(dx/maxTilt,-1,1),y:Physics.clamp(dy/maxTilt,-1,1)};}
  function combineInput(){const sensor=getSensorInput();state.sensorInput=sensor;let x=sensor.x,y=sensor.y;if(Math.abs(state.keyInput.x)+Math.abs(state.keyInput.y)>.01){x=state.keyInput.x;y=state.keyInput.y;}if(state.touchInput.active){x=state.touchInput.x;y=state.touchInput.y;}const mag=Math.hypot(x,y);if(mag>1){x/=mag;y/=mag;}state.input.x=x;state.input.y=y;tiltDot.style.transform=`translate(${x*13}px,${y*13}px)`;}
  function update(dt){if(!state.running||state.paused)return;state.levelTime+=dt;state.totalTime+=dt;state.respawnLock=Math.max(0,state.respawnLock-dt);combineInput();const difficulty=1+Math.floor((state.level-1)/Levels.length)*.08+Math.min(.18,state.level*.008),result=Physics.step(state.ball,state.world,state.input,dt,difficulty);if(result.wallHit&&Math.hypot(state.ball.vx,state.ball.vy)>1.8)audio(170,.025,'square',.012);if(result.bumperHit){addParticles(result.bumperHit.x,result.bumperHit.y,'#ffe66d',7);audio(330,.055,'square',.035);vibrate(8);}for(const shard of state.world.shards)if(!shard.collected&&Physics.circleHit(state.ball,shard,.03))collectShard(shard);for(const pit of state.world.pits)if(Physics.circleHit(state.ball,pit,-.08)){loseLife('NEL VUOTO!');break;}if(state.world.shards.every(s=>s.collected)&&Physics.circleHit(state.ball,state.world.goal,.02))clearLevel();state.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt*1.45;});state.particles=state.particles.filter(p=>p.life>0);updateHud();}
  function frame(now){const dt=Math.min(.04,Math.max(0,(now-state.last)/1000));state.last=now;update(dt);ctx.clearRect(0,0,state.cssW,state.cssH);ctx.save();ctx.translate(state.offsetX||0,state.offsetY||0);Renderer.render(ctx,state,now);ctx.restore();requestAnimationFrame(frame);}
  startBtn.addEventListener('click',async()=>{if(state.sensor.permission==='unknown'){const granted=await requestSensorPermission();if(granted)await calibrate(false);else setBanner('SENSORE NON ATTIVO • USA TOUCH');}startGame();});
  calibrateBtn.addEventListener('click',async()=>{if(state.sensor.permission==='unknown')await requestSensorPermission();if(state.sensor.permission==='granted')calibrate(true);else setBanner('USA TOUCH O FRECCE');});
  pauseBtn.addEventListener('click',()=>{if(!state.running)return;state.paused=!state.paused;pauseBtn.textContent=state.paused?'▶':'Ⅱ';if(!state.paused)state.last=performance.now();});muteBtn.addEventListener('click',()=>{state.mute=!state.mute;muteBtn.textContent=state.mute?'🔇':'🔊';});
  const keys=new Set(),updateKeys=()=>{state.keyInput.x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);state.keyInput.y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);};window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);updateKeys();}if(e.code==='KeyP'||e.code==='Space'){e.preventDefault();pauseBtn.click();}},{passive:false});window.addEventListener('keyup',e=>{keys.delete(e.code);updateKeys();});
  let pointer=null;canvas.addEventListener('pointerdown',e=>{if(!state.running||state.paused)return;const r=canvas.getBoundingClientRect();pointer={id:e.pointerId,x:e.clientX-r.left,y:e.clientY-r.top};canvas.setPointerCapture?.(e.pointerId);touchStick.hidden=false;touchStick.style.left=`${pointer.x}px`;touchStick.style.top=`${pointer.y}px`;state.touchInput.active=true;state.touchInput.x=state.touchInput.y=0;});canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const r=canvas.getBoundingClientRect();let dx=e.clientX-r.left-pointer.x,dy=e.clientY-r.top-pointer.y;const max=34,d=Math.hypot(dx,dy);if(d>max){dx*=max/d;dy*=max/d;}state.touchInput.x=dx/max;state.touchInput.y=dy/max;stickKnob.style.transform=`translate(${dx}px,${dy}px)`;});const releasePointer=e=>{if(!pointer||(e&&pointer.id!==e.pointerId))return;pointer=null;state.touchInput.active=false;state.touchInput.x=state.touchInput.y=0;touchStick.hidden=true;stickKnob.style.transform='';};canvas.addEventListener('pointerup',releasePointer);canvas.addEventListener('pointercancel',releasePointer);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.paused){state.paused=true;pauseBtn.textContent='▶';}});
  window.addEventListener('rwg:continue-game',e=>{const d=e.detail||{};state.score=Number.isFinite(d.score)?d.score:state.score;state.lives=Math.max(1,state.lives);state.ball.x=state.world.start.x;state.ball.y=state.world.start.y;state.ball.vx=state.ball.vy=0;state.respawnLock=1.3;state.paused=false;state.running=true;pauseBtn.textContent='Ⅱ';overlay.classList.remove('visible');state.last=performance.now();updateHud();setBanner('CONTINUE!');});
  if('ResizeObserver' in window)new ResizeObserver(resize).observe(wrap);else window.addEventListener('resize',resize,{passive:true});
  loadLevel(1,false);updateHud();requestAnimationFrame(frame);
})();
