(() => {
  'use strict';
  const TAU=Math.PI*2;
  function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(r,w/2,h/2));}
  function drawGrid(ctx,w,h,t,cell){ctx.save();ctx.strokeStyle='rgba(101,231,255,.055)';ctx.lineWidth=1;const drift=(t*.018)%cell;for(let x=-cell+drift;x<w+cell;x+=cell){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=-cell+drift;y<h+cell;y+=cell){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.restore();}
  function render(ctx,state,now){
    const{cell,world,ball}=state,w=state.boardW||state.cssW,h=state.boardH||state.cssH;ctx.clearRect(0,0,w,h);
    const bg=ctx.createRadialGradient(w*.5,h*.38,0,w*.5,h*.45,Math.max(w,h)*.7);bg.addColorStop(0,'#102c47');bg.addColorStop(.55,'#071527');bg.addColorStop(1,'#02050d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);drawGrid(ctx,w,h,now,Math.max(18,cell));
    for(const ice of world.ice){ctx.save();const x=ice.x*cell,y=ice.y*cell;ctx.fillStyle='rgba(101,231,255,.12)';ctx.fillRect(x,y,cell,cell);ctx.strokeStyle='rgba(190,250,255,.22)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+cell*.15,y+cell*.8);ctx.lineTo(x+cell*.8,y+cell*.2);ctx.stroke();ctx.restore();}
    for(const boost of world.boosts){const x=boost.cx*cell,y=boost.cy*cell;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(boost.dy,boost.dx));ctx.fillStyle='rgba(255,94,207,.13)';ctx.fillRect(-cell*.5,-cell*.5,cell,cell);ctx.strokeStyle='#ff5ecf';ctx.lineWidth=Math.max(1.5,cell*.05);ctx.shadowColor='#ff5ecf';ctx.shadowBlur=8;for(let k=-1;k<=1;k++){const ox=k*cell*.18;ctx.beginPath();ctx.moveTo(ox-cell*.13,-cell*.18);ctx.lineTo(ox+cell*.12,0);ctx.lineTo(ox-cell*.13,cell*.18);ctx.stroke();}ctx.restore();}
    for(const wall of world.walls){const x=wall.x*cell,y=wall.y*cell,ww=wall.w*cell,hh=wall.h*cell;ctx.save();roundedRect(ctx,x+.7,y+.7,ww-1.4,hh-1.4,Math.max(2,cell*.13));const grad=ctx.createLinearGradient(x,y,x+ww,y+hh);grad.addColorStop(0,'#183a5f');grad.addColorStop(1,'#0a1a31');ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='rgba(101,231,255,.55)';ctx.lineWidth=Math.max(1,cell*.055);ctx.shadowColor='#65e7ff';ctx.shadowBlur=5;ctx.stroke();ctx.restore();}
    for(const pit of world.pits){const x=pit.x*cell,y=pit.y*cell,r=pit.r*cell;ctx.save();const g=ctx.createRadialGradient(x,y,r*.1,x,y,r);g.addColorStop(0,'#000');g.addColorStop(.58,'#020207');g.addColorStop(.75,'#561d56');g.addColorStop(1,'rgba(255,94,207,.08)');ctx.fillStyle=g;ctx.shadowColor='#ff5ecf';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.restore();}
    for(const bumper of world.bumpers){const x=bumper.x*cell,y=bumper.y*cell,r=bumper.r*cell;ctx.save();ctx.shadowColor='#ffe66d';ctx.shadowBlur=14;ctx.fillStyle='#ffe66d';ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.fillStyle='#7b4a05';ctx.beginPath();ctx.arc(x,y,r*.47,0,TAU);ctx.fill();ctx.restore();}
    for(const shard of world.shards){if(shard.collected)continue;const x=shard.x*cell,y=shard.y*cell;ctx.save();ctx.translate(x,y);ctx.rotate(now*.0022+shard.phase);const pulse=1+Math.sin(now*.006+shard.phase)*.1;ctx.scale(pulse,pulse);ctx.fillStyle='#7cffb2';ctx.shadowColor='#7cffb2';ctx.shadowBlur=11;ctx.beginPath();ctx.moveTo(0,-cell*.26);ctx.lineTo(cell*.18,0);ctx.lineTo(0,cell*.26);ctx.lineTo(-cell*.18,0);ctx.closePath();ctx.fill();ctx.restore();}
    const goal=world.goal;ctx.save();const gx=goal.x*cell,gy=goal.y*cell,gr=goal.r*cell,gateOpen=world.shards.every(s=>s.collected);ctx.strokeStyle=gateOpen?'#7cffb2':'#ff5ecf';ctx.lineWidth=Math.max(2,cell*.08);ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=16;for(let i=0;i<3;i++){ctx.globalAlpha=.9-i*.22;ctx.beginPath();ctx.arc(gx,gy,gr*(1-i*.17),now*.002+i,now*.002+i+Math.PI*1.55);ctx.stroke();}ctx.restore();
    for(const p of state.particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=6;ctx.fillRect(p.x*cell,p.y*cell,p.size*cell,p.size*cell);ctx.restore();}
    ctx.save();const bx=ball.x*cell,by=ball.y*cell,br=ball.r*cell,mg=ctx.createRadialGradient(bx-br*.35,by-br*.45,br*.08,bx,by,br);mg.addColorStop(0,'#fff');mg.addColorStop(.26,'#bff8ff');mg.addColorStop(.65,'#65e7ff');mg.addColorStop(1,'#176b94');ctx.fillStyle=mg;ctx.shadowColor='#65e7ff';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(bx,by,br,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=Math.max(1,br*.1);ctx.stroke();ctx.restore();
    if(!world.shards.every(s=>s.collected)){const remaining=world.shards.filter(s=>!s.collected).length;ctx.save();ctx.fillStyle='rgba(2,5,13,.72)';roundedRect(ctx,8,h-29,126,21,8);ctx.fill();ctx.fillStyle='#d9ffe8';ctx.font='800 9px ui-monospace, monospace';ctx.fillText(`CRISTALLI: ${remaining}`,16,h-15);ctx.restore();}
  }
  window.NeonTiltRender=Object.freeze({render});
})();
