export default Object.freeze({
  blockDrop:{ended:'Partita terminata.',summary:'Punteggio {score} • {lines} linee • livello {level}.',resume:'{lines} linee • livello {level} • {score} punti'},
  bubbleBurst:{levelWord:'LIVELLO',completedWord:'COMPLETATO!',levelBanner:'LIVELLO {level} • {name}',levelTimer:'Tempo livello {elapsed}. Tempo ottimale {optimal}.',levelTimerTitle:'Tempo ottimale: {optimal} • soglia +25%: {threshold}',nextBubble:'Prossima bolla: {bubble}',levelComplete:'LIVELLO {level} COMPLETATO!',levelPoints:'Punti livello: {points}',time:'Tempo: {time}',bonus:'Bonus: +{rate}% (+{points})',noBonus:'Bonus: NO BONUS!',total:'Totale: {points} punti!',danger:'Le bolle hanno raggiunto la linea di pericolo.',summary:'Punteggio {score} • livello {level}.',normal:'normale',bomb:'bomba',colorClear:'elimina colore',comboBomb:'COMBO ×5 • BOMBA PRONTA!',armor:'ARMOR BUBBLES!',star:'STAR BUBBLES!',prism:'PRISM BUBBLES!',structureDown:'↓ STRUTTURA IN DISCESA!',descentIn:'↓ DISCESA IN {seconds}s',dangerLabel:'DANGER',pauseLabel:'PAUSA',resume:'livello {level} • {score} punti'},
  mazeMunch:{ready:'PRONTO',levelComplete:'LIVELLO COMPLETO',ended:'Caccia terminata.',summary:'Punteggio {score} • livello {level}.',go:'VAI!',pause:'PAUSA',hunting:'IN CACCIA',continue:'CONTINUA!',resumed:'PARTITA RIPRESA',resume:'livello {level} • {lives} vite • {score} punti'},
  neonRally:{won:'Hai vinto {player}-{cpu}.',cpuWon:'La CPU vince {cpu}-{player}.',bestRally:'Best rally: {best}.',yourPoint:'PUNTO TU',cpuPoint:'PUNTO CPU',pause:'PAUSA',go:'VIA',continue:'CONTINUA!'},
  neonSnake:{level:'LEVEL {level}',bonusOrb:'BONUS ORB!',shieldOrb:'SHIELD ORB!',bonus:'BONUS!',bonusLost:'BONUS PERSO',shieldActive:'SHIELD ATTIVO',shieldSaved:'SHIELD SALVA!',ended:'Corsa terminata.',summary:'Punteggio {score} • livello {level}.',go:'VIA!',continue:'CONTINUA!',resumed:'PARTITA RIPRESA',resume:'livello {level} • lunghezza {length} • {score} punti'},
  neonTilt:{level:'LEVEL {level} • {name}',fall:'CADUTA!',pit:'NEL VUOTO!',sensorUnavailable:'SENSORE NON ATTIVO • USA TOUCH',useTouchOrKeys:'USA TOUCH O FRECCE',portalOpen:'PORTALE APERTO!',clear:'CLEAR +{points}',ended:'Run terminata al livello {level}. Punteggio {score}.',holdPhone:'TIENI IL TELEFONO COMODO...',calibrated:'CALIBRATO!',resumed:'PARTITA RIPRESA',continue:'CONTINUA!',resume:'livello {level} • {lives} vite • {score} punti'},
  prismBreaker:{cycle:'ciclo {cycle}',cycleSpeed:'CYCLE {cycle} • VELOCITÀ +12%',bossDown:'BOSS {boss} DOWN!',levelClear:'LEVEL {level} CLEAR!',lifeLost:'{reason} • {lives} {lifeLabel}',life:'VITA',lives:'VITE',ended:'Run terminata.',summary:'Punteggio {score} • livello {level}.',catchLaunch:'CATCH • TAP PER LANCIARE',expand:'EXPAND!',multi:'MULTIBALL!',slow:'SLOW!',laser:'LASER!',catch:'CATCH!',extraLife:'EXTRA LIFE!',resumed:'PARTITA RIPRESA',continue:'CONTINUA!',resume:'livello {level} • {lives} vite • {score} punti'},
  solitaire:{title:'Solitario',variantClassic:'Classico',variantFreeCell:'FreeCell',subtitleKlondike:'Klondike • pesca 1',subtitleFreeCell:'FreeCell • 4 celle libere',minimal:'MIN.',essentialDeck:'MAZZO ESSENZIALE',classicDeck:'MAZZO CLASSICO',newDealGoodLuck:'NUOVA MANO • BUONA FORTUNA!',moveUndone:'MOSSA ANNULLATA',stockReloaded:'MAZZO RICARICATO',invalidMove:'MOSSA NON VALIDA',autoFinishReady:'VIA LIBERA • COMPLETAMENTO AUTOMATICO!',autoFinishInterrupted:'COMPLETAMENTO INTERROTTO',noHint:'NESSUN SUGGERIMENTO IMMEDIATO',hintWasteFoundation:'Porta lo scarto in fondazione',hintCellFoundation:'Porta la cella in fondazione',hintFoundation:'Carta disponibile per la fondazione',hintWasteTableau:'Sposta lo scarto sul tableau',hintFreeCellTableau:'Libera una cella sulla cascata',hintSequence:'C’è una sequenza spostabile',hintFreeColumn:'Libera la colonna usando una cella',hintDraw:'Pesca una carta',hintReload:'Ricarica il mazzo',moves:'{count} mosse',foundationProgress:'{count}/52 in fondazione',pause:'PAUSA',resumeAction:'Riprendi',classic:'CLASS.',gameVariant:'SOLITARIO • {variant}',fourCells:'4 CELLE',eightColumns:'8 COLONNE',drawOne:'PESCA 1',sevenColumns:'7 COLONNE',cards52:'52 CARTE',coveredCard:'Carta coperta',stock:'Mazzo: {count} carte',reloadStock:'Ricarica il mazzo',emptyStock:'Mazzo vuoto',foundation:'Fondazione {suit}: {card}',empty:'vuota',free:'LIBERA',freeCell:'Cella libera {cell}: {card}',column:'Colonna {column}',bestTime:'MIGLIOR TEMPO {time}',resumed:'PARTITA PRECEDENTE RIPRESA',resume:'{variant} • {score} punti • {time}'},
  starSwarm:{points:'PUNTI',livesLabel:'VITE',weapon:'ARMA',bossTime:'BOSS TIME',omega:'OMEGA SWARM ANNIHILATO • OVERDRIVE SBLOCCATO!',oneUpLives:'1UP! • VITE {lives}',bossIncoming:'WARNING • BOSS INCOMING',waveClear:'WAVE CLEAR +{points}',campaignComplete:'CAMPAGNA COMPLETATA!!',bossDefeated:'BOSS N. {boss} SCONFITTO!!',tapContinue:'TOCCA PER CONTINUARE',ended:'Sciame terminato.',summary:'Punteggio {score} • livello {level}.',continue:'CONTINUA!',resume:'livello {level} • {lives} vite • {score} punti'},
  theGreatEmpire:{foodShort:'CIBO',woodShort:'LEGNO',goldShort:'ORO',populationShort:'POP',levelShort:'LIV',ageShort:'ETÀ',scoreShort:'PUNTI',clubman:'GUERRIERO',archer:'ARCIERE',cavalry:'CAVALLERIA',house:'CASA',tower:'TORRE',villagers:'CONTADINI',soldiers:'SOLDATI',attack:'ASSALTO',stoneAge:'PIETRA',bronzeAge:'BRONZO',ironAge:'FERRO',stoneAgeName:'ETÀ DELLA PIETRA',bronzeAgeName:'ETÀ DEL BRONZO',ironAgeName:'ETÀ DEL FERRO',cost:'RISORSE INSUFFICIENTI',populationNeeded:'SERVONO PIÙ CASE',townBusy:'CENTRO CITTÀ OCCUPATO',ageLocked:'ETÀ NON ANCORA RAGGIUNTA',spaceBusy:'SPAZIO OCCUPATO',tooManyBuildings:'TROPPI EDIFICI',maxAgeReached:'SEI GIÀ NELL’ETÀ DEL FERRO',siteOpen:'CANTIERE APERTO',unavailable:'NON DISPONIBILE',advancing:'AVANZAMENTO {seconds}s',villager:'CONTADINO',maxAge:'ETÀ MAX',defend:'DIFENDI IL CENTRO CITTÀ',level:'LIVELLO {level}',enemyWave:'ONDATA NEMICA!',built:'COSTRUZIONE COMPLETATA',buildingLost:'EDIFICIO DISTRUTTO!',campDestroyed:'ACCAMPAMENTO DISTRUTTO!',placeTower:'TOCCA DOVE COSTRUIRE LA TORRE',placeHouse:'TOCCA DOVE COSTRUIRE LA CASA',ageProgress:'AVANZAMENTO IN CORSO',noVillager:'NESSUN CONTADINO',noSoldier:'NESSUN SOLDATO',assault:'ASSALTO: {count}',needSoldiers:'SERVONO SOLDATI',continue:'CONTINUA!',cityCenter:'CENTRO CITTÀ',camp:'ACCAMPAMENTO',resume:'Livello {level} • {age} • {score} punti'}
});
