import italian from '../it/games.mjs';
import english from '../en/games.mjs';
const translations=Object.freeze({
'blockDrop.ended':'Partida terminada.','blockDrop.summary':'Puntuación {score} • {lines} líneas • nivel {level}.','blockDrop.resume':'{lines} líneas • nivel {level} • {score} puntos',
'bubbleBurst.levelWord':'NIVEL','bubbleBurst.completedWord':'¡COMPLETADO!','bubbleBurst.levelBanner':'NIVEL {level} • {name}','bubbleBurst.levelTimer':'Tiempo del nivel {elapsed}. Tiempo objetivo {optimal}.','bubbleBurst.levelTimerTitle':'Tiempo objetivo: {optimal} • umbral +25%: {threshold}','bubbleBurst.nextBubble':'Próxima burbuja: {bubble}','bubbleBurst.levelComplete':'¡NIVEL {level} COMPLETADO!','bubbleBurst.levelPoints':'Puntos del nivel: {points}','bubbleBurst.time':'Tiempo: {time}','bubbleBurst.total':'¡Total: {points} puntos!','bubbleBurst.danger':'Las burbujas han alcanzado la línea de peligro.','bubbleBurst.summary':'Puntuación {score} • nivel {level}.','bubbleBurst.normal':'normal','bubbleBurst.bomb':'bomba','bubbleBurst.colorClear':'elimina color','bubbleBurst.comboBomb':'COMBO ×5 • ¡BOMBA LISTA!','bubbleBurst.structureDown':'↓ ¡LA ESTRUCTURA DESCIENDE!','bubbleBurst.descentIn':'↓ DESCENSO EN {seconds}s','bubbleBurst.pauseLabel':'PAUSA','bubbleBurst.resume':'nivel {level} • {score} puntos',
'mazeMunch.ready':'LISTO','mazeMunch.levelComplete':'NIVEL COMPLETADO','mazeMunch.ended':'La persecución ha terminado.','mazeMunch.summary':'Puntuación {score} • nivel {level}.','mazeMunch.go':'¡YA!','mazeMunch.pause':'PAUSA','mazeMunch.hunting':'DE CAZA','mazeMunch.continue':'¡CONTINUAR!','mazeMunch.resumed':'PARTIDA REANUDADA','mazeMunch.resume':'nivel {level} • {lives} vidas • {score} puntos',
'neonRally.won':'Has ganado {player}-{cpu}.','neonRally.cpuWon':'La CPU gana {cpu}-{player}.','neonRally.yourPoint':'PUNTO PARA TI','neonRally.cpuPoint':'PUNTO PARA LA CPU','neonRally.pause':'PAUSA','neonRally.go':'YA','neonRally.continue':'¡CONTINUAR!',
'neonSnake.bonusLost':'BONUS PERDIDO','neonSnake.shieldActive':'ESCUDO ACTIVO','neonSnake.shieldSaved':'¡EL ESCUDO TE HA SALVADO!','neonSnake.ended':'La carrera ha terminado.','neonSnake.summary':'Puntuación {score} • nivel {level}.','neonSnake.go':'¡YA!','neonSnake.continue':'¡CONTINUAR!','neonSnake.resumed':'PARTIDA REANUDADA','neonSnake.resume':'nivel {level} • longitud {length} • {score} puntos',
'neonTilt.fall':'¡CAÍDA!','neonTilt.pit':'¡AL VACÍO!','neonTilt.sensorUnavailable':'SENSOR NO DISPONIBLE • USA TOUCH','neonTilt.useTouchOrKeys':'USA TOUCH O LAS FLECHAS','neonTilt.portalOpen':'¡PORTAL ABIERTO!','neonTilt.ended':'Partida terminada en el nivel {level}. Puntuación {score}.','neonTilt.holdPhone':'SUJETA EL TELÉFONO CÓMODAMENTE...','neonTilt.calibrated':'¡CALIBRADO!','neonTilt.resumed':'PARTIDA REANUDADA','neonTilt.continue':'¡CONTINUAR!','neonTilt.resume':'nivel {level} • {lives} vidas • {score} puntos',
'prismBreaker.cycle':'ciclo {cycle}','prismBreaker.cycleSpeed':'CICLO {cycle} • VELOCIDAD +12%','prismBreaker.life':'VIDA','prismBreaker.lives':'VIDAS','prismBreaker.ended':'Partida terminada.','prismBreaker.summary':'Puntuación {score} • nivel {level}.','prismBreaker.catchLaunch':'ATRAPA • TOCA PARA LANZAR','prismBreaker.resumed':'PARTIDA REANUDADA','prismBreaker.continue':'¡CONTINUAR!','prismBreaker.resume':'nivel {level} • {lives} vidas • {score} puntos',
'solitaire.title':'Solitario','solitaire.variantClassic':'Clásico','solitaire.subtitleKlondike':'Klondike • roba 1','solitaire.subtitleFreeCell':'FreeCell • 4 celdas libres','solitaire.essentialDeck':'BARAJA ESENCIAL','solitaire.classicDeck':'BARAJA CLÁSICA','solitaire.newDealGoodLuck':'¡NUEVA PARTIDA • BUENA SUERTE!','solitaire.moveUndone':'MOVIMIENTO DESHECHO','solitaire.stockReloaded':'MAZO RECARGADO','solitaire.invalidMove':'MOVIMIENTO NO VÁLIDO','solitaire.autoFinishReady':'VÍA LIBRE • ¡FINAL AUTOMÁTICO!','solitaire.autoFinishInterrupted':'FINAL AUTOMÁTICO INTERRUMPIDO','solitaire.noHint':'NINGUNA PISTA INMEDIATA','solitaire.hintWasteFoundation':'Mueve la carta del descarte a una fundación','solitaire.hintCellFoundation':'Mueve la carta de la celda libre a una fundación','solitaire.hintFoundation':'Puedes mover una carta a una fundación','solitaire.hintWasteTableau':'Mueve la carta del descarte al tablero','solitaire.hintFreeCellTableau':'Libera una celda en el tablero','solitaire.hintSequence':'Puedes mover una secuencia','solitaire.hintFreeColumn':'Libera la columna usando una celda','solitaire.hintDraw':'Roba una carta','solitaire.hintReload':'Recarga el mazo','solitaire.moves':'{count} movimientos','solitaire.foundationProgress':'{count}/52 en las fundaciones','solitaire.pause':'PAUSA','solitaire.resumeAction':'Reanudar','solitaire.classic':'CLÁSICO','solitaire.gameVariant':'SOLITARIO • {variant}','solitaire.fourCells':'4 CELDAS','solitaire.eightColumns':'8 COLUMNAS','solitaire.drawOne':'ROBA 1','solitaire.sevenColumns':'7 COLUMNAS','solitaire.cards52':'52 CARTAS','solitaire.coveredCard':'Carta boca abajo','solitaire.stock':'Mazo: {count} cartas','solitaire.reloadStock':'Recargar mazo','solitaire.emptyStock':'Mazo vacío','solitaire.foundation':'Fundación de {suit}: {card}','solitaire.empty':'vacía','solitaire.free':'LIBRE','solitaire.freeCell':'Celda libre {cell}: {card}','solitaire.column':'Columna {column}','solitaire.bestTime':'MEJOR TIEMPO {time}','solitaire.resumed':'PARTIDA ANTERIOR REANUDADA','solitaire.resume':'{variant} • {score} puntos • {time}',
'starSwarm.points':'PUNTUACIÓN','starSwarm.livesLabel':'VIDAS','starSwarm.weapon':'ARMA','starSwarm.omega':'OMEGA SWARM ANIQUILADO • ¡OVERDRIVE DESBLOQUEADO!','starSwarm.oneUpLives':'¡1UP! • VIDAS {lives}','starSwarm.campaignComplete':'¡¡CAMPAÑA COMPLETADA!!','starSwarm.bossDefeated':'¡¡BOSS N.º {boss} DERROTADO!!','starSwarm.tapContinue':'TOCA PARA CONTINUAR','starSwarm.ended':'El enjambre te ha atrapado.','starSwarm.summary':'Puntuación {score} • nivel {level}.','starSwarm.continue':'¡CONTINUAR!','starSwarm.resume':'nivel {level} • {lives} vidas • {score} puntos',
'theGreatEmpire.foodShort':'COMIDA','theGreatEmpire.woodShort':'MADERA','theGreatEmpire.goldShort':'ORO','theGreatEmpire.levelShort':'NIV','theGreatEmpire.ageShort':'ERA','theGreatEmpire.scoreShort':'PUNTOS','theGreatEmpire.clubman':'GUERRERO','theGreatEmpire.archer':'ARQUERO','theGreatEmpire.cavalry':'CABALLERÍA','theGreatEmpire.house':'CASA','theGreatEmpire.tower':'TORRE','theGreatEmpire.villagers':'ALDEANOS','theGreatEmpire.soldiers':'SOLDADOS','theGreatEmpire.attack':'ASALTO','theGreatEmpire.stoneAge':'PIEDRA','theGreatEmpire.bronzeAge':'BRONCE','theGreatEmpire.ironAge':'HIERRO','theGreatEmpire.stoneAgeName':'EDAD DE PIEDRA','theGreatEmpire.bronzeAgeName':'EDAD DE BRONCE','theGreatEmpire.ironAgeName':'EDAD DE HIERRO','theGreatEmpire.cost':'RECURSOS INSUFICIENTES','theGreatEmpire.populationNeeded':'CONSTRUYE MÁS CASAS','theGreatEmpire.townBusy':'CENTRO URBANO OCUPADO','theGreatEmpire.ageLocked':'ERA TODAVÍA NO ALCANZADA','theGreatEmpire.spaceBusy':'ESPACIO OCUPADO','theGreatEmpire.tooManyBuildings':'DEMASIADOS EDIFICIOS','theGreatEmpire.maxAgeReached':'YA ESTÁS EN LA EDAD DE HIERRO','theGreatEmpire.siteOpen':'OBRA ABIERTA','theGreatEmpire.unavailable':'NO DISPONIBLE','theGreatEmpire.advancing':'AVANZANDO {seconds}s','theGreatEmpire.villager':'ALDEANO','theGreatEmpire.maxAge':'ERA MÁX.','theGreatEmpire.defend':'DEFIENDE EL CENTRO URBANO','theGreatEmpire.level':'NIVEL {level}','theGreatEmpire.enemyWave':'¡OLEADA ENEMIGA!','theGreatEmpire.built':'CONSTRUCCIÓN COMPLETADA','theGreatEmpire.buildingLost':'¡EDIFICIO DESTRUIDO!','theGreatEmpire.campDestroyed':'¡CAMPAMENTO ENEMIGO DESTRUIDO!','theGreatEmpire.placeTower':'TOCA PARA COLOCAR LA TORRE','theGreatEmpire.placeHouse':'TOCA PARA COLOCAR LA CASA','theGreatEmpire.ageProgress':'AVANCE EN CURSO','theGreatEmpire.noVillager':'SIN ALDEANOS','theGreatEmpire.noSoldier':'SIN SOLDADOS','theGreatEmpire.assault':'ASALTO: {count}','theGreatEmpire.needSoldiers':'NECESITAS SOLDADOS','theGreatEmpire.continue':'¡CONTINUAR!','theGreatEmpire.cityCenter':'CENTRO URBANO','theGreatEmpire.camp':'CAMPAMENTO ENEMIGO','theGreatEmpire.resume':'Nivel {level} • {age} • {score} puntos'
});
const clone=value=>Array.isArray(value)?value.map(clone):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,child])=>[key,clone(child)])):value;
const result=clone(italian),set=(key,value)=>{const parts=key.split('.'),leaf=parts.pop(),parent=parts.reduce((node,part)=>node[part],result);parent[leaf]=value;};for(const [key,value]of Object.entries(translations))set(key,value);
const flatten=(value,prefix='',out=[])=>{for(const [key,child]of Object.entries(value)){const next=prefix?`${prefix}.${key}`:key;if(typeof child==='string')out.push([next,child]);else flatten(child,next,out);}return out;};const get=(catalog,key)=>key.split('.').reduce((node,part)=>node?.[part],catalog);
const missing=flatten(italian).map(([key])=>key).filter(key=>!Object.hasOwn(translations,key)&&get(italian,key)!==get(english,key));if(missing.length)throw new Error(`Spanish game translations missing: ${missing.join(', ')}`);
export default Object.freeze(result);
