import italian from '../it/shared.mjs';
import english from '../en/shared.mjs';

const translations=Object.freeze({
'core.backToGames':'Volver a todos los juegos de RetroWebGames','core.globalControls':'Controles generales del juego','core.pause':'Pausa','core.resume':'Reanudar','core.cancel':'CANCELAR','core.back':'ATRÁS','core.score':'PUNTUACIÓN','core.level':'NIVEL','core.activeTime':'TIEMPO ACTIVO','core.play':'JUGAR','core.replay':'JUGAR DE NUEVO','core.backToMenu':'VOLVER AL MENÚ','core.movement':'MOVIMIENTO','core.analogControl':'Control analógico','core.mazeJoystickHint':'Usa el joystick, desliza por el laberinto o utiliza las flechas / WASD. Recoge todos los puntos y activa los nodos de energía.','core.snakeJoystickHint':'Usa el joystick, desliza o utiliza las flechas / WASD para moverte. Mantén TURBO pulsado para duplicar la velocidad.','core.tiltJoystickHint':'El joystick y las flechas están siempre disponibles.',
'share.label':'Compartir','share.game':'Compartir {game}','share.inviteGame':'🎮 Estoy jugando a {game} en RetroWebGames. ¡Pruébalo tú también!','share.thisGame':'Compartir este juego','share.result':'¡Comparte tu resultado!','share.whatsapp':'Compartir en WhatsApp','share.facebook':'Compartir en Facebook','share.x':'Compartir en X','share.telegram':'Compartir en Telegram','share.linkedin':'Compartir en LinkedIn','share.more':'Más opciones para compartir','share.copied':'Enlace copiado','share.homeInvite':'🎮 Prueba RetroWebGames: ¡juegos arcade gratis directamente en tu navegador!','share.homeDescription':'Juegos arcade gratis inspirados en los clásicos, directamente en tu navegador.',
'session.saved':'PARTIDA GUARDADA','session.question':'¿Quieres reanudar la partida anterior?','session.yes':'Sí',
'pause.title':'JUEGO EN PAUSA','pause.safe':'Tu partida está a salvo. Reanúdala cuando quieras.','pause.resume':'REANUDAR','pause.end':'TERMINAR PARTIDA','pause.score':'PUNTUACIÓN','pause.activeTime':'TIEMPO ACTIVO','pause.registering':'GUARDANDO PUNTUACIÓN…','pause.ended':'PARTIDA TERMINADA','pause.eligible':'Esta puntuación se enviará a High Scores ({score} puntos, {duration} de juego activo).','pause.ineligible':'Este resultado no entrará en High Scores: necesitas más de {score} puntos y al menos 0:45 de juego activo.','pause.warning':'Terminar cerrará definitivamente la partida actual.','pause.terminate':'SÍ, TERMINAR PARTIDA','pause.finalWarning':'Confirmación final: esta acción no se puede deshacer.','pause.finalCopy':'La partida actual terminará y se eliminará la partida guardada.','pause.final':'CONFIRMAR DEFINITIVAMENTE',
'gameOver.skip':'TOCA PARA CONTINUAR','gameOver.ended':'PARTIDA TERMINADA','gameOver.summary':'Resumen de la partida','gameOver.achievementsAria':'Logros desbloqueados','gameOver.continue':'Continuar por 1','gameOver.newGame':'Nueva partida','gameOver.chooseGame':'Elegir otro juego','gameOver.credits':'Obtener créditos','gameOver.achievementRecord':'Nuevo récord','gameOver.achievement1k':'1.000 puntos','gameOver.achievement5k':'5.000 puntos','gameOver.achievementLevel3':'Nivel 3+','gameOver.achievementMarathon':'3 minutos','gameOver.achievementLines10':'10 líneas','gameOver.shareMatch':'¡He terminado {player}–{cpu} en {game}! ¿Puedes superarme?','gameOver.shareScore':'¡He conseguido {score} puntos en {game}! ¿Puedes superarme?','gameOver.continueOne':' He usado 1 continuación.','gameOver.continueMany':' He usado {count} continuaciones.','gameOver.result':'RESULTADO','gameOver.points':'PUNTOS','gameOver.levelsCleared':'NIVELES SUPERADOS','gameOver.lines':'LÍNEAS','gameOver.continuesUsed':'CONTINUACIONES USADAS','gameOver.time':'TIEMPO',
'leaderboard.highScoresFor':'High Scores de {game}','leaderboard.refresh':'Actualizar clasificación','leaderboard.top3':'🏆 TOP 3 GLOBAL','leaderboard.top3For':'Top 3 global de {game}','leaderboard.podiumFor':'Podio global de {game}','leaderboard.connectingShort':'CONECTANDO…','leaderboard.variants':'VARIANTES','leaderboard.refreshTop3':'Actualizar Top 3 de {game}','leaderboard.connecting':'CONECTANDO CON EL ARCADE…','leaderboard.emptyPodium':'SIN RÉCORDS • EL PODIO TE ESPERA','leaderboard.empty':'SIN RÉCORDS • ¡ESTRENA LA CLASIFICACIÓN!','leaderboard.unavailable':'CLASIFICACIÓN NO DISPONIBLE','leaderboard.retry':'CLASIFICACIÓN NO DISPONIBLE • REINTENTAR','leaderboard.cached':'ÚLTIMA ACTUALIZACIÓN GUARDADA','leaderboard.cachedPlural':'ÚLTIMOS DATOS GUARDADOS','leaderboard.loadMore':'CARGANDO MÁS RÉCORDS…','leaderboard.scrollMore':'↓ DESLIZA PARA VER MÁS HIGH SCORES','leaderboard.scrollAria':'High Scores desplazables. Carga 10 posiciones cada vez.','leaderboard.scrollContinue':'DESLIZA PARA CONTINUAR','leaderboard.allRecords':'TODOS LOS RÉCORDS','leaderboard.highScoresUnavailable':'HIGH SCORES NO DISPONIBLES • REINTENTAR','leaderboard.enterName':'INTRODUCE TU NOMBRE','leaderboard.entryCopy':'Firma este récord: la próxima vez lo haremos automáticamente.','leaderboard.nicknameAria':'Apodo arcade','leaderboard.nicknamePlaceholder':'TU NOMBRE','leaderboard.register':'GUARDAR RÉCORD','leaderboard.registering':'GUARDANDO…','leaderboard.registeredAt':'GUARDADO • POSICIÓN #{position}','leaderboard.registered':'¡RÉCORD GUARDADO!','leaderboard.invalid':'DATOS NO VÁLIDOS','leaderboard.nicknameInvalid':'USA 3–12 LETRAS, NÚMEROS, ESPACIOS, - O _','leaderboard.queued':'GUARDADO • ENVÍO AUTOMÁTICO AL VOLVER A ESTAR ONLINE','leaderboard.positionUpdating':'ACTUALIZANDO POSICIÓN','leaderboard.globalPositionLabel':'POSICIÓN GLOBAL','leaderboard.topTen':'¡Estás en el TOP TEN!','leaderboard.globalPosition':'Posición global #{position}','leaderboard.pending':'Récord pendiente de envío','leaderboard.rankPendingCopy':'Récord guardado: actualizaremos tu posición cuando vuelvas a estar online.','leaderboard.rankTopTenCopy':'¡Genial! Tu récord brilla entre los mejores.','leaderboard.rankDefaultCopy':'¿Otro intento? La cima está cada vez más cerca.',
'profile.credits':'Créditos disponibles','profile.creditsCount':'Créditos disponibles: {count}','profile.insufficient':'Créditos insuficientes','profile.neededOne':'Necesitas 1 crédito para continuar esta partida.','profile.neededMany':'Necesitas {count} créditos para continuar esta partida.','profile.available':'{count} disponibles','profile.availableSuffix':'disponibles','profile.customizeAvatar':'Personaliza tu avatar',
'orientation.title':'Gira el teléfono','orientation.portrait':'en vertical','orientation.copy':'Este juego está diseñado para el modo vertical. Gira el teléfono para continuar.','orientation.paused':'PARTIDA EN PAUSA • NO HAS PERDIDO NINGÚN PROGRESO',
'avatar.none':'NINGUNO','avatar.unsaved':'CAMBIOS SIN GUARDAR','avatar.saved':'GUARDADO','avatar.savedPlayer':'JUGADOR GUARDADO ✓','avatar.savePlayer':'GUARDAR JUGADOR','avatar.createPlayer':'CREA TU JUGADOR','avatar.pageIntro':'Crea tu personaje a partir de un stickman arcade y equípalo con estilo y ropa. Tu avatar te acompaña por todo RetroWebGames.','avatar.navigation':'Navegación del avatar','avatar.preview':'Vista previa del avatar','avatar.avatarStage':'Vista previa de tu avatar. Arrastra para girarlo.','avatar.resetView':'Restablecer vista','avatar.rotateHint':'ARRASTRA PARA GIRAR','avatar.loadoutSummary':'Resumen del equipamiento','avatar.undoChanges':'DESHACER CAMBIOS','avatar.customize':'Personalización del avatar','avatar.chooseStyle':'ELIGE TU ESTILO','avatar.slots':'{count} RANURAS','avatar.categories':'Categorías del avatar','avatar.body':'CUERPO','avatar.head':'CABEZA','avatar.bodyStructure':'CUERPO DEL JUGADOR','avatar.bodyStructureCopy':'La silueta se mantiene clara incluso en la pequeña insignia del juego.','avatar.build':'CONSTITUCIÓN','avatar.skin':'TONO DE PIEL','avatar.expression':'EXPRESIÓN','avatar.headCopy':'El rostro, el pelo y los colores mantienen el estilo arcade sin perder claridad.','avatar.eyes':'OJOS','avatar.hair':'PELO','avatar.hairColor':'COLOR DE PELO','avatar.outfitCopy':'La camiseta, los pantalones y los zapatos se superponen al esqueleto stickman.','avatar.topColor':'COLOR DE CAMISETA','avatar.trousers':'PANTALONES','avatar.trousersColor':'COLOR DE PANTALONES','avatar.shoes':'ZAPATOS','avatar.gearCopy':'Las ranuras de equipo son independientes: combina gafas, tocado, emblema y aura.','avatar.eyewear':'GAFAS','avatar.headgear':'TOCADO','avatar.emblem':'EMBLEMA','avatar.storedDevice':'Guardado en este dispositivo','avatar.profileNote':'El avatar está vinculado a la identidad local anónima del navegador. La versión 2 migra automáticamente el avatar anterior y separa las ranuras de equipo para ofrecer más opciones de personalización.',
'pwa.noticeAria':'Instalar RetroWebGames','pwa.title':'RWG siempre a un toque','pwa.copy':'Añádelo a tu pantalla de inicio y tendrás el arcade al instante.','pwa.iosGuidance':'En iPhone o iPad: toca Compartir ⤴︎ y luego “Añadir a pantalla de inicio”.','pwa.browserGuidance':'Abre el menú del navegador y elige “Instalar aplicación” o “Añadir a pantalla de inicio”.','pwa.install':'INSTALAR','pwa.close':'Cerrar aviso de instalación','pwa.cardTitle':'Lleva el arcade a tu pantalla de inicio','pwa.cardCopy':'Un toque y estás dentro. Sin aplicaciones pesadas: solo un acceso directo diminuto.','pwa.installWebApp':'INSTALAR WEB APP',
'home.eyebrow':'ARCADE MÓVIL • CERO INSTALACIONES','home.intro':'Videojuegos y retrogames originales gratis para jugar directamente en tu navegador. Elige un web game y entra en acción: controles táctiles, partidas rápidas y récords guardados en tu dispositivo.','home.gamesAvailable':'{count} JUEGOS DISPONIBLES','home.gamesAria':'Juegos disponibles','home.partnerTitle':'Sitios asociados','home.shareHome':'Compartir RetroWebGames','home.inviteFriend':'Invita a un amigo a jugar','home.other':'Más'
});
const clone=value=>Array.isArray(value)?value.map(clone):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,child])=>[key,clone(child)])):value;
const result=clone(italian);const set=(key,value)=>{const parts=key.split('.'),leaf=parts.pop(),parent=parts.reduce((node,part)=>node[part],result);parent[leaf]=value;};
for(const [key,value] of Object.entries(translations))set(key,value);
const sourceKeys=[];const walk=(value,prefix='')=>{for(const [key,child]of Object.entries(value)){const next=prefix?`${prefix}.${key}`:key;if(typeof child==='string')sourceKeys.push(next);else walk(child,next);}};walk(italian);
const get=(catalog,key)=>key.split('.').reduce((node,part)=>node?.[part],catalog);
const missing=sourceKeys.filter(key=>!Object.hasOwn(translations,key)&&get(italian,key)!==get(english,key));
if(missing.length)throw new Error(`Spanish shared translations missing: ${missing.join(', ')}`);
export default Object.freeze(result);
