export default Object.freeze({
  blockDrop:{ended:'Game over.',summary:'Score {score} • {lines} lines • level {level}.',resume:'{lines} lines • level {level} • {score} points'},
  bubbleBurst:{levelWord:'LEVEL',completedWord:'COMPLETE!',levelBanner:'LEVEL {level} • {name}',levelTimer:'Level time {elapsed}. Target time {optimal}.',levelTimerTitle:'Target time: {optimal} • +25% threshold: {threshold}',nextBubble:'Next bubble: {bubble}',levelComplete:'LEVEL {level} COMPLETE!',levelPoints:'Level points: {points}',time:'Time: {time}',bonus:'Bonus: +{rate}% (+{points})',noBonus:'Bonus: NO BONUS!',total:'Total: {points} points!',danger:'The bubbles reached the danger line.',summary:'Score {score} • level {level}.',normal:'standard',bomb:'bomb',colorClear:'color clear',comboBomb:'COMBO ×5 • BOMB READY!',armor:'ARMOR BUBBLES!',star:'STAR BUBBLES!',prism:'PRISM BUBBLES!',structureDown:'↓ STRUCTURE DROPPING!',descentIn:'↓ DROP IN {seconds}s',dangerLabel:'DANGER',pauseLabel:'PAUSED',resume:'level {level} • {score} points'},
  mazeMunch:{ready:'READY',levelComplete:'LEVEL COMPLETE',ended:'The chase is over.',summary:'Score {score} • level {level}.',go:'GO!',pause:'PAUSED',hunting:'HUNTING',continue:'CONTINUE!',resumed:'GAME RESUMED',resume:'level {level} • {lives} lives • {score} points'},
  neonRally:{won:'You won {player}-{cpu}.',cpuWon:'CPU wins {cpu}-{player}.',bestRally:'Best rally: {best}.',yourPoint:'YOUR POINT',cpuPoint:'CPU POINT',pause:'PAUSED',go:'GO',continue:'CONTINUE!'},
  neonSnake:{level:'LEVEL {level}',bonusOrb:'BONUS ORB!',shieldOrb:'SHIELD ORB!',bonus:'BONUS!',bonusLost:'BONUS LOST',shieldActive:'SHIELD ACTIVE',shieldSaved:'SHIELD SAVED YOU!',ended:'Run over.',summary:'Score {score} • level {level}.',go:'GO!',continue:'CONTINUE!',resumed:'GAME RESUMED',resume:'level {level} • length {length} • {score} points'},
  neonTilt:{level:'LEVEL {level} • {name}',fall:'FALL!',pit:'INTO THE PIT!',sensorUnavailable:'SENSOR UNAVAILABLE • USE TOUCH',useTouchOrKeys:'USE TOUCH OR ARROW KEYS',portalOpen:'PORTAL OPEN!',clear:'CLEAR +{points}',ended:'Run ended at level {level}. Score {score}.',holdPhone:'HOLD YOUR PHONE COMFORTABLY...',calibrated:'CALIBRATED!',resumed:'GAME RESUMED',continue:'CONTINUE!',resume:'level {level} • {lives} lives • {score} points'},
  prismBreaker:{cycle:'cycle {cycle}',cycleSpeed:'CYCLE {cycle} • SPEED +12%',bossDown:'BOSS {boss} DOWN!',levelClear:'LEVEL {level} CLEAR!',lifeLost:'{reason} • {lives} {lifeLabel}',life:'LIFE',lives:'LIVES',ended:'Run over.',summary:'Score {score} • level {level}.',catchLaunch:'CATCH • TAP TO LAUNCH',expand:'EXPAND!',multi:'MULTIBALL!',slow:'SLOW!',laser:'LASER!',catch:'CATCH!',extraLife:'EXTRA LIFE!',resumed:'GAME RESUMED',continue:'CONTINUE!',resume:'level {level} • {lives} lives • {score} points'},
  solitaire:{title:'Solitaire',variantClassic:'Classic',variantFreeCell:'FreeCell',subtitleKlondike:'Klondike • draw 1',subtitleFreeCell:'FreeCell • 4 free cells',minimal:'MIN.',essentialDeck:'ESSENTIAL DECK',classicDeck:'CLASSIC DECK',newDealGoodLuck:'NEW DEAL • GOOD LUCK!',moveUndone:'MOVE UNDONE',stockReloaded:'STOCK RELOADED',invalidMove:'INVALID MOVE',autoFinishReady:'CLEAR PATH • AUTO-FINISH!',autoFinishInterrupted:'AUTO-FINISH INTERRUPTED',noHint:'NO IMMEDIATE HINT',hintWasteFoundation:'Move the waste card to a foundation',hintCellFoundation:'Move the free-cell card to a foundation',hintFoundation:'A card can move to a foundation',hintWasteTableau:'Move the waste card to the tableau',hintFreeCellTableau:'Free a cell onto the tableau',hintSequence:'A sequence can be moved',hintFreeColumn:'Free the column with a cell',hintDraw:'Draw a card',hintReload:'Reload the stock',moves:'{count} moves',foundationProgress:'{count}/52 in foundations',pause:'PAUSED',resumeAction:'Resume',classic:'CLASSIC',gameVariant:'SOLITAIRE • {variant}',fourCells:'4 CELLS',eightColumns:'8 COLUMNS',drawOne:'DRAW 1',sevenColumns:'7 COLUMNS',cards52:'52 CARDS',coveredCard:'Face-down card',stock:'Stock: {count} cards',reloadStock:'Reload stock',emptyStock:'Empty stock',foundation:'{suit} foundation: {card}',empty:'empty',free:'FREE',freeCell:'Free cell {cell}: {card}',column:'Column {column}',bestTime:'BEST TIME {time}',resumed:'PREVIOUS GAME RESUMED',resume:'{variant} • {score} points • {time}'},
  starSwarm:{points:'SCORE',livesLabel:'LIVES',weapon:'WEAPON',bossTime:'BOSS TIME',omega:'OMEGA SWARM ANNIHILATED • OVERDRIVE UNLOCKED!',oneUpLives:'1UP! • LIVES {lives}',bossIncoming:'WARNING • BOSS INCOMING',waveClear:'WAVE CLEAR +{points}',campaignComplete:'CAMPAIGN COMPLETE!!',bossDefeated:'BOSS NO. {boss} DEFEATED!!',tapContinue:'TAP TO CONTINUE',ended:'The swarm got you.',summary:'Score {score} • level {level}.',continue:'CONTINUE!',resume:'level {level} • {lives} lives • {score} points'},
  theGreatEmpire:{foodShort:'FOOD',woodShort:'WOOD',goldShort:'GOLD',populationShort:'POP',levelShort:'LVL',ageShort:'AGE',scoreShort:'SCORE',clubman:'WARRIOR',archer:'ARCHER',cavalry:'CAVALRY',house:'HOUSE',tower:'TOWER',villagers:'VILLAGERS',soldiers:'SOLDIERS',attack:'ASSAULT',stoneAge:'STONE',bronzeAge:'BRONZE',ironAge:'IRON',stoneAgeName:'STONE AGE',bronzeAgeName:'BRONZE AGE',ironAgeName:'IRON AGE',cost:'NOT ENOUGH RESOURCES',populationNeeded:'BUILD MORE HOUSES',townBusy:'TOWN CENTER BUSY',ageLocked:'AGE NOT REACHED YET',spaceBusy:'SPACE OCCUPIED',tooManyBuildings:'TOO MANY BUILDINGS',maxAgeReached:'YOU ARE ALREADY IN THE IRON AGE',siteOpen:'BUILD SITE OPEN',unavailable:'UNAVAILABLE',advancing:'ADVANCING {seconds}s',villager:'VILLAGER',maxAge:'MAX AGE',defend:'DEFEND THE TOWN CENTER',level:'LEVEL {level}',enemyWave:'ENEMY WAVE!',built:'BUILDING COMPLETE',buildingLost:'BUILDING DESTROYED!',campDestroyed:'ENEMY CAMP DESTROYED!',placeTower:'TAP TO PLACE THE TOWER',placeHouse:'TAP TO PLACE THE HOUSE',ageProgress:'ADVANCEMENT IN PROGRESS',noVillager:'NO VILLAGERS',noSoldier:'NO SOLDIERS',assault:'ASSAULT: {count}',needSoldiers:'YOU NEED SOLDIERS',continue:'CONTINUE!',cityCenter:'TOWN CENTER',camp:'ENEMY CAMP',resume:'Level {level} • {age} • {score} points'}
});
