(() => {
  'use strict';
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),scoreEl=document.getElementById('score'),levelEl=document.getElementById('level'),comboEl=document.getElementById('combo'),bestEl=document.getElementById('best'),shieldBadge=document.getElementById('shieldBadge'),bannerEl=document.getElementById('banner'),overlay=document.getElementById('overlay'),overlayText=document.getElementById('overlayText'),startBtn=document.getElementById('startBtn'),pauseBtn=document.getElementById('pauseBtn'),muteBtn=document.getElementById('muteBtn'),boostBtn=document.getElementById('boostBtn');
  const COLS=20,ROWS=28,RESUME_SCHEMA=1,BASE_STEP_MS=1000,LEVEL_SPEED_FACTOR=.965,MIN_STEP_MS=170,TURBO_MULTIPLIER=2;
  const DIR={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}},OPP={up:'down',down:'up',left:'right',right:'left'};
  let W=390,H=620,DPR=1,cell=20,ox=0,oy=0,running=false,paused=false,muted=false;
  let snake=[],dir='right',queuedDir='right',food=null,bonus=null,shieldOrb=null,obstacles=[];
  let score=0,level=1,foods=0,combo=1,shield=false,best=Number(localStorage.getItem('rwgNeonSnakeBest')||0);
  let accumulator=0,last=0,lastEatAt=0,bonusTTL=0,shieldTTL=0,bannerTimer=0,particles=[],swipe=null,audio=null,turboActive=false;
  const key=p=>`${p.x},${p.y}`,same=(a,b)=>a&&b&&a.x===b.x&&a.y===b.y,rand=n=>Math.floor(Math.random()*n),markSessionDirty=reason=>window.RWGSession?.markDirty?.(reason);
  function ensureAudio(){if(audio)return;const AC=window.AudioContext||window.webkitAudioContext;if(AC)audio=new AC();}
  function tone(freq,duration=.05,type='square',volume=.02,end=freq){if(muted)return;ensureAudio();if(!audio)return;if(audio.state==='suspended')audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
  function resize(){const r=canvas.getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=Math.max(1,Math.floor(W*DPR));canvas.height=Math.max(1,Math.floor(H*DPR));ctx.setTransform(DPR,0,0,DPR,0,0);cell=Math.min(W/COLS,H/ROWS);ox=(W-cell*COLS)/2;oy=(H-cell*ROWS)/2;draw();}
  function occupiedSet(includeHead=true){const s=new Set();snake.forEach((p,i)=>{if(includeHead||i>0)s.add(key(p));});obstacles.forEach(p=>s.add(key(p)));if(food)s.add(key(food));if(bonus)s.add(key(bonus));if(shieldOrb)s.add(key(shieldOrb));return s;}
  function emptyCell(extra=new Set()){const blocked=occupiedSet();for(const x of extra)blocked.add(x);for(let tries=0;tries<1000;tries++){const p={x:rand(COLS),y:rand(ROWS)};if(!blocked.has(key(p)))return p;}return null;}
  function baseStepMs(){return Math.max(MIN_STEP_MS,BASE_STEP_MS*Math.pow(LEVEL_SPEED_FACTOR,level-1));}
  function movementIntervalMs(){return baseStepMs()/(turboActive?TURBO_MULTIPLIER:1);}
  function comboWindowMs(){return Math.max(3200,baseStepMs()*16);}
  function pickupLifetimeSeconds(stepBudget,minimum){return Math.max(minimum,baseStepMs()*stepBudget/1000);}
  function setTurbo(active){const next=Boolean(active&&running&&!paused);if(next===turboActive)return;turboActive=next;boostBtn.classList.toggle('is-active',next);boostBtn.setAttribute('aria-pressed',String(next));}
  function spawnFood(){food=emptyCell();}function spawnBonus(){bonus=emptyCell();bonusTTL=pickupLifetimeSeconds(42,6.5);if(bonus)announce('BONUS ORB!');}function spawnShield(){shieldOrb=emptyCell();shieldTTL=pickupLifetimeSeconds(49,7.5);if(shieldOrb)announce('SHIELD DISPONIBILE');}
  function addObstacles(){const target=Math.min(16,Math.max(0,(level-2)*2));while(obstacles.length<target){const p=emptyCell();if(!p)break;const head=snake[0];if(Math.abs(p.x-head.x)+Math.abs(p.y-head.y)<5)continue;obstacles.push(p);}}
  function resetGame(){setTurbo(false);const cx=Math.floor(COLS/2),cy=Math.floor(ROWS/2);snake=[{x:cx+1,y:cy},{x:cx,y:cy},{x:cx-1,y:cy},{x:cx-2,y:cy}];dir=queuedDir='right';obstacles=[];food=bonus=shieldOrb=null;score=0;level=1;foods=0;combo=1;shield=false;accumulator=0;lastEatAt=0;bonusTTL=shieldTTL=0;particles=[];spawnFood();updateHud();}
  function updateHud(){scoreEl.textContent=score.toLocaleString('it-IT');levelEl.textContent=level;comboEl.textContent=`×${combo}`;bestEl.textContent=best.toLocaleString('it-IT');shieldBadge.hidden=!shield;}
  function setDir(name){if(!DIR[name]||OPP[dir]===name)return;queuedDir=name;}
  function announce(text,seconds=1.05){bannerEl.textContent=text;bannerEl.classList.add('show');bannerTimer=seconds;}
  function burst(p,color,count=10){const cx=ox+(p.x+.5)*cell,cy=oy+(p.y+.5)*cell;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*90;particles.push({x:cx,y:cy,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.45+Math.random()*.35,color,size:1+Math.random()*2.4});}}
  function eatFood(now){foods++;const quick=lastEatAt&&now-lastEatAt<=comboWindowMs();combo=quick?Math.min(5,combo+1):1;lastEatAt=now;score+=100*combo;burst(food,'#7cffb2',12);tone(430+combo*70,.055,'triangle',.025,680+combo*70);food=null;const newLevel=Math.floor(foods/5)+1;if(newLevel>level){level=newLevel;addObstacles();announce(`LEVEL ${level}`);tone(480,.16,'triangle',.035,920);}if(foods%5===0&&!bonus)spawnBonus();if(foods%8===0&&!shieldOrb&&!shield)spawnShield();spawnFood();updateHud();markSessionDirty('food');}
  function eatBonus(){score+=450*Math.max(1,combo);combo=Math.min(5,combo+1);burst(bonus,'#ffe66d',20);bonus=null;bonusTTL=0;announce('BONUS!');tone(660,.14,'sine',.04,1120);navigator.vibrate?.([12,18,18]);updateHud();markSessionDirty('bonus');}
  function eatShield(){shield=true;burst(shieldOrb,'#65e7ff',20);shieldOrb=null;shieldTTL=0;announce('SHIELD ATTIVO');tone(520,.18,'sine',.04,1040);updateHud();markSessionDirty('shield');}
  function collisionAt(p){if(p.x<0||p.x>=COLS||p.y<0||p.y>=ROWS)return true;if(obstacles.some(o=>same(o,p)))return true;return snake.slice(1,-1).some(s=>same(s,p));}
  function safeResetAfterShield(){shield=false;combo=1;const cx=Math.floor(COLS/2),cy=Math.floor(ROWS/2);snake=[{x:cx+1,y:cy},{x:cx,y:cy},{x:cx-1,y:cy},{x:cx-2,y:cy}];dir=queuedDir='right';obstacles=obstacles.filter(o=>Math.abs(o.x-cx)+Math.abs(o.y-cy)>5);addObstacles();announce('SHIELD SALVA!');tone(160,.18,'sawtooth',.035,520);navigator.vibrate?.([30,25,20]);updateHud();markSessionDirty('shield-save');}
  function step(now){if(!running||paused)return;if(OPP[dir]!==queuedDir)dir=queuedDir;const d=DIR[dir],next={x:snake[0].x+d.x,y:snake[0].y+d.y};if(collisionAt(next)){if(shield)safeResetAfterShield();else endGame();return;}snake.unshift(next);let grow=false;if(same(next,food)){grow=true;eatFood(now);}if(same(next,bonus)){grow=true;eatBonus();}if(same(next,shieldOrb)){grow=true;eatShield();}if(!grow)snake.pop();}
  function endGame(){setTurbo(false);running=false;paused=false;best=Math.max(best,score);localStorage.setItem('rwgNeonSnakeBest',String(best));updateHud();overlayText.innerHTML=`Corsa terminata.<br>Punteggio <strong>${score.toLocaleString('it-IT')}</strong> • livello ${level} • lunghezza ${snake.length}.`;startBtn.textContent='RIGIOCA';pauseBtn.textContent='Ⅱ';overlay.classList.add('visible');tone(120,.28,'sawtooth',.045,55);navigator.vibrate?.([45,40,70]);const detail={game:'Neon Snake',score,level,best,maxCombo:combo,length:snake.length};window.dispatchEvent(new CustomEvent('rwg:game-ended',{detail}));requestAnimationFrame(()=>window.RWGGameOver?.open?.(detail));}
  function update(dt,now){if(!running||paused)return;accumulator+=dt*1000;const interval=movementIntervalMs();while(accumulator>=interval&&running&&!paused){accumulator-=interval;step(now);}if(lastEatAt&&now-lastEatAt>comboWindowMs()+300&&combo!==1){combo=1;updateHud();}if(bonus){bonusTTL-=dt;if(bonusTTL<=0){bonus=null;announce('BONUS PERSO',.65);markSessionDirty('bonus-expired');}}if(shieldOrb){shieldTTL-=dt;if(shieldTTL<=0){shieldOrb=null;markSessionDirty('shield-expired');}}if(bannerTimer>0){bannerTimer-=dt;if(bannerTimer<=0)bannerEl.classList.remove('show');}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.06,dt);p.vy*=Math.pow(.06,dt);p.life-=dt;if(p.life<=0)particles.splice(i,1);}}
  function rounded(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();}
  function drawCell(p,fill,glow=null,scale=.72){const size=cell*scale,x=ox+(p.x+.5)*cell-size/2,y=oy+(p.y+.5)*cell-size/2;ctx.save();if(glow){ctx.shadowBlur=cell*.65;ctx.shadowColor=glow;}rounded(x,y,size,size,Math.max(2,size*.22),fill);ctx.restore();}
  function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#06152a');g.addColorStop(.55,'#020915');g.addColorStop(1,'#01040a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(101,231,255,.055)';ctx.lineWidth=1;for(let x=0;x<=COLS;x++){const px=ox+x*cell;ctx.beginPath();ctx.moveTo(px,oy);ctx.lineTo(px,oy+ROWS*cell);ctx.stroke();}for(let y=0;y<=ROWS;y++){const py=oy+y*cell;ctx.beginPath();ctx.moveTo(ox,py);ctx.lineTo(ox+COLS*cell,py);ctx.stroke();}obstacles.forEach(o=>{drawCell(o,'#27364d','#526b8d',.78);const cx=ox+(o.x+.5)*cell,cy=oy+(o.y+.5)*cell;ctx.strokeStyle='rgba(101,231,255,.26)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx-cell*.18,cy-cell*.18);ctx.lineTo(cx+cell*.18,cy+cell*.18);ctx.stroke();});if(food)drawCell(food,'#7cffb2','#7cffb2',.58);if(bonus)drawCell(bonus,'#ffe66d','#ffe66d',.62+Math.sin(performance.now()/110)*.1);if(shieldOrb){const cx=ox+(shieldOrb.x+.5)*cell,cy=oy+(shieldOrb.y+.5)*cell;ctx.save();ctx.shadowBlur=16;ctx.shadowColor='#65e7ff';ctx.strokeStyle='#65e7ff';ctx.lineWidth=Math.max(2,cell*.12);ctx.beginPath();ctx.arc(cx,cy,cell*.29,0,Math.PI*2);ctx.stroke();ctx.restore();}for(let i=snake.length-1;i>=0;i--){const p=snake[i],t=i/Math.max(1,snake.length-1),color=i===0?'#eafff2':`hsl(${150+t*35} 95% ${62-t*18}%)`;drawCell(p,color,i===0?'#7cffb2':null,i===0?.84:.72);}if(snake[0]){const h=snake[0],cx=ox+(h.x+.5)*cell,cy=oy+(h.y+.5)*cell,d=DIR[dir],side={x:-d.y,y:d.x};ctx.fillStyle='#04110a';for(const s of[-1,1]){ctx.beginPath();ctx.arc(cx+d.x*cell*.16+side.x*s*cell*.15,cy+d.y*cell*.16+side.y*s*cell*.15,Math.max(1.2,cell*.055),0,Math.PI*2);ctx.fill();}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.8);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}ctx.globalAlpha=1;}
  function loop(ts){const dt=Math.min(.04,(ts-last)/1000||0);last=ts;update(dt,ts);draw();requestAnimationFrame(loop);}
  function startGame(){window.RWGSession?.clear?.();ensureAudio();resetGame();running=true;paused=false;last=performance.now();pauseBtn.textContent='Ⅱ';startBtn.textContent='RIGIOCA';overlay.classList.remove('visible');announce('VIA!');markSessionDirty('new-game');}
  function togglePause(){if(!running)return;if(!paused)setTurbo(false);paused=!paused;pauseBtn.textContent=paused?'▶':'Ⅱ';if(paused){overlayText.textContent='Partita in pausa.';startBtn.textContent='RIPRENDI';overlay.classList.add('visible');window.RWGSession?.saveNow?.('pause');}else{last=performance.now();accumulator=0;startBtn.textContent='RIGIOCA';overlay.classList.remove('visible');announce('VIA!',.55);}}
  function validPoint(p){return p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.x<COLS&&p.y>=0&&p.y<ROWS;}
  function validateResumeState(s){if(!s||s.schema!==RESUME_SCHEMA||!Array.isArray(s.snake)||s.snake.length<2||s.snake.some(p=>!validPoint(p))||new Set(s.snake.map(key)).size!==s.snake.length)return false;if(!DIR[s.dir]||!DIR[s.queuedDir]||!Array.isArray(s.obstacles)||s.obstacles.some(p=>!validPoint(p))||new Set(s.obstacles.map(key)).size!==s.obstacles.length)return false;for(const p of[s.food,s.bonus,s.shieldOrb])if(p!==null&&!validPoint(p))return false;const occupied=new Set([...s.snake,...s.obstacles].map(key));for(const p of[s.food,s.bonus,s.shieldOrb])if(p&&occupied.has(key(p)))return false;if(![s.score,s.level,s.foods,s.combo,s.accumulator,s.bonusTTL,s.shieldTTL,s.lastEatAgo].every(Number.isFinite))return false;if(s.score<0||s.foods<0||s.level!==Math.floor(s.foods/5)+1||s.combo<1||s.combo>5||s.accumulator<0||s.bonusTTL<0||s.shieldTTL<0||s.lastEatAgo<0)return false;return typeof s.shield==='boolean';}
  function serializeResumeState(){return{schema:RESUME_SCHEMA,snake:snake.map(p=>({...p})),dir,queuedDir,food:food?{...food}:null,bonus:bonus?{...bonus}:null,shieldOrb:shieldOrb?{...shieldOrb}:null,obstacles:obstacles.map(p=>({...p})),score,level,foods,combo,shield,accumulator,bonusTTL,shieldTTL,lastEatAgo:lastEatAt?Math.max(0,performance.now()-lastEatAt):0};}
  function restoreResumeState(s){if(!validateResumeState(s))return false;setTurbo(false);snake=s.snake.map(p=>({...p}));dir=s.dir;queuedDir=s.queuedDir;food=s.food?{...s.food}:null;bonus=s.bonus?{...s.bonus}:null;shieldOrb=s.shieldOrb?{...s.shieldOrb}:null;obstacles=s.obstacles.map(p=>({...p}));score=Math.floor(s.score);level=Math.floor(s.level);foods=Math.floor(s.foods);combo=Math.floor(s.combo);shield=s.shield;accumulator=s.accumulator;bonusTTL=s.bonusTTL;shieldTTL=s.shieldTTL;lastEatAt=s.lastEatAgo?performance.now()-s.lastEatAgo:0;particles=[];running=true;paused=false;overlay.classList.remove('visible');startBtn.textContent='RIGIOCA';pauseBtn.textContent='Ⅱ';last=performance.now();updateHud();resize();draw();announce('PARTITA RIPRESA',.8);return true;}
  const resumeAdapter=Object.freeze({id:'neon-snake',version:1,compatibility:'neon-snake-state-v1-20x28',isInProgress:()=>running,serialize:serializeResumeState,validate:validateResumeState,restore:restoreResumeState,startFresh:startGame,describe:s=>`livello ${s.level} • lunghezza ${s.snake?.length||0} • ${Math.floor(s.score||0).toLocaleString('it-IT')} punti`});window.RWGResumeAdapter=resumeAdapter;window.RWGSession?.register?.(resumeAdapter);
  startBtn.addEventListener('click',()=>{if(running&&paused){togglePause();return;}startGame();});pauseBtn.addEventListener('click',togglePause);muteBtn.addEventListener('click',()=>{muted=!muted;muteBtn.textContent=muted?'🔇':'🔊';});
  document.querySelectorAll('#controls [data-dir]').forEach(btn=>btn.addEventListener('pointerdown',e=>{e.preventDefault();setDir(btn.dataset.dir);}));
  boostBtn.addEventListener('pointerdown',e=>{e.preventDefault();boostBtn.setPointerCapture?.(e.pointerId);setTurbo(true);});
  for(const eventName of['pointerup','pointercancel','lostpointercapture'])boostBtn.addEventListener(eventName,()=>setTurbo(false));
  canvas.addEventListener('pointerdown',e=>{swipe={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!swipe)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.hypot(dx,dy)<18)return;setDir(Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down'));});canvas.addEventListener('pointercancel',()=>{swipe=null;});
  window.addEventListener('keydown',e=>{if(e.key==='Shift'){e.preventDefault();setTurbo(true);return;}const k=e.key.toLowerCase(),name=k==='arrowup'||k==='w'?'up':k==='arrowdown'||k==='s'?'down':k==='arrowleft'||k==='a'?'left':k==='arrowright'||k==='d'?'right':null;if(name){e.preventDefault();setDir(name);}else if((k==='p'||k===' ')&&running){e.preventDefault();togglePause();}});
  window.addEventListener('keyup',e=>{if(e.key==='Shift')setTurbo(false);});window.addEventListener('blur',()=>setTurbo(false));
  window.addEventListener('rwg:continue-game',e=>{setTurbo(false);score=Math.max(0,Math.floor(e.detail?.score??score));combo=1;shield=false;bonus=null;shieldOrb=null;bonusTTL=shieldTTL=0;accumulator=0;lastEatAt=0;const cx=Math.floor(COLS/2),cy=Math.floor(ROWS/2);snake=[{x:cx+1,y:cy},{x:cx,y:cy},{x:cx-1,y:cy},{x:cx-2,y:cy}];dir=queuedDir='right';obstacles=obstacles.filter(o=>Math.abs(o.x-cx)+Math.abs(o.y-cy)>5);addObstacles();if(!food||snake.some(s=>same(s,food))||obstacles.some(o=>same(o,food)))spawnFood();running=true;paused=false;overlay.classList.remove('visible');startBtn.textContent='RIGIOCA';pauseBtn.textContent='Ⅱ';last=performance.now();updateHud();ensureAudio();announce('CONTINUA!',1.1);tone(520,.16,'triangle',.035,900);markSessionDirty('credit-continue');});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){setTurbo(false);if(running&&!paused)togglePause();}});window.addEventListener('resize',resize);bestEl.textContent=best.toLocaleString('it-IT');resize();requestAnimationFrame(loop);
})();
