#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
const root=process.cwd(),failures=[];const must=(c,m)=>{if(!c)failures.push(m);},read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const gamesRoot=path.join(root,'games');
const gamePages=fs.readdirSync(gamesRoot,{withFileTypes:true}).filter(e=>e.isDirectory()&&fs.existsSync(path.join(gamesRoot,e.name,'index.html'))).map(e=>`games/${e.name}/index.html`).filter(rel=>/<body[^>]*data-rwg-game=["']true["']/i.test(read(rel))).sort();
must(gamePages.length>0,'No RWG game pages discovered');const session=read('rwg-session.js'),sessionCss=read('rwg-session.css'),hud=read('game-hud.js');
for(const marker of ["const STORAGE_PREFIX = 'rwg.session.v2:'",'const ENVELOPE_SCHEMA = 2','const DIRTY_DEBOUNCE_MS = 750','const HEARTBEAT_MS = 5000','adapter.compatibility',"adapter.validate(envelope.payload, envelope)",'requestIdleCallback','pagehide','beforeunload','freeze','navigation','rwg:game-ended','rwg:session-completed','Vuoi continuare la partita precedente?','data-rwg-resume-no','data-rwg-resume-yes'])must(session.includes(marker),`rwg-session.js missing central persistence marker: ${marker}`);
must(session.includes("const LEGACY_PREFIXES = ['rwg.session.v1:']"),'Session v2 must invalidate obsolete v1 storage');must(session.includes("for (const method of ['serialize', 'restore', 'validate', 'isInProgress', 'startFresh'])"),'Shared session register must require complete adapter contract');must(session.includes('encoded.length > MAX_SNAPSHOT_BYTES'),'Shared session snapshot-size guard missing');must(!/requestAnimationFrame\([^\n]{0,120}saveNow/.test(session),'Shared session must never save per animation frame');must(sessionCss.includes('.rwg-resume-no')&&sessionCss.includes('.rwg-resume-yes'),'Shared resume action styles missing');must(sessionCss.indexOf('.rwg-resume-no')<sessionCss.indexOf('.rwg-resume-yes'),'Resume modal must keep No before Sì');must(sessionCss.includes('#c92f43')&&sessionCss.includes('#35cf79'),'Resume modal red/green emphasis missing');must(hud.includes('rwg-session.js')&&hud.includes('rwg-session.css')&&hud.includes('loadSession();'),'game-hud.js must bootstrap centralized RWGSession');
const adapterSummaries=[];for(const rel of gamePages){const html=read(rel),gameDir=path.posix.dirname(rel),hudIndex=html.indexOf('../../game-hud.js');must(hudIndex>=0,`${rel}: shared game-hud.js missing`);const scripts=[...html.matchAll(/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi)].map(m=>({src:m[1],index:m.index}));const sources=[];for(const item of scripts.filter(i=>i.index<hudIndex&&!i.src.startsWith('../')&&!/^https?:/i.test(i.src))){const cleanSrc=item.src.replace(/[?#].*$/,''),file=path.posix.normalize(`${gameDir}/${cleanSrc}`),abs=path.join(root,file);if(fs.existsSync(abs))sources.push({file,source:fs.readFileSync(abs,'utf8')});}const adapterSources=sources.filter(i=>i.source.includes('RWGResumeAdapter'));must(adapterSources.length>=1,`${rel}: no RWGResumeAdapter loaded before shared HUD`);if(!adapterSources.length)continue;const joined=adapterSources.map(i=>i.source).join('\n');for(const marker of ['compatibility:','serialize','validate','restore','startFresh','isInProgress'])must(joined.includes(marker),`${rel}: resume adapter missing ${marker}`);must(/version\s*:\s*[1-9]\d*/.test(joined),`${rel}: adapter needs positive version`);must(/compatibility\s*:\s*['"`][^'"`]+['"`]/.test(joined),`${rel}: adapter needs compatibility token`);must(!joined.includes('localStorage.setItem(`rwg.session')&&!joined.includes("localStorage.setItem('rwg.session"),`${rel}: adapter must not duplicate central storage`);for(const {file} of adapterSources){const result=spawnSync(process.execPath,['--check',path.join(root,file)],{encoding:'utf8'});must(result.status===0,`${file}: node --check failed`);}adapterSummaries.push(`${path.basename(gameDir)} → ${adapterSources.map(i=>path.basename(i.file)).join(', ')}`);}
for(const rel of ['scripts/validate-shared-controls.mjs','scripts/validate-shared-pause.mjs']){const result=spawnSync(process.execPath,[path.join(root,rel),'--nested'],{encoding:'utf8'});must(result.status===0,`${rel}: shared platform validator failed: ${(result.stderr||result.stdout||'').trim()}`);}
if(failures.length){console.error(`\nRWG resumable-session validation FAILED (${failures.length})\n`);failures.forEach(f=>console.error(`  ✗ ${f}`));process.exit(1);}console.log('RWG resumable-session validation OK');console.log(`  ✓ ${gamePages.length}/${gamePages.length} discovered games expose a versioned compatible resume adapter`);console.log('  ✓ shared pause/control validators are included in repository-wide validation');for(const s of adapterSummaries)console.log(`  ✓ ${s}`);
